### ISSUE TITLE
comboSample implementation details

### ISSUE THREAD

**Issue by Kornel** [jwood000/RcppAlgos#17]
Can you provide some references or documentation how `comboSample` is implemented? I admit only taking a glance at the source.

I'm genuinely curious how to approach this problem of getting a random combination. It works amazingly fast for the sample sizes I had to sample, e.g. 300k choose 300 (I don't even want to think how big the search space is :D but I suppose this does not matter).

edit: I suppose it could be the one mentioned here https://stackoverflow.com/questions/2394246/algorithm-to-select-a-single-random-combination-of-values ?

**Comment by jwood000** [comment]
@Kornel,

I briefly looked at the answers and they all seem quite a bit different than how I approached it except for a brief mention at the top of this [answer](<https://stackoverflow.com/a/2394308/4408538>). However, that post goes on to implement a different algorithm for permutations. I must admit, my implementation was purely my own and I didn't even know they were called [combinadics](<https://en.wikipedia.org/wiki/Combinatorial_number_system>) until I read the answer I linked above, so I don't have any great references. I'm not saying it's a unique approach and there could be much better ways to attack this.

The approach implemented in `RcppAlgos` is based off of the ability to generate the _n<sup>th</sup>_ lexicographical combination. The only random call made is on the total number of combinations.  Think of `combn(5, 3)`. We have a total of `choose(5, 3) = 10` combinations. If we wanted 3 random combinations of this, we could first call `sample(choose(5, 3), 3)` to obtain the indices of the lexicographical combinations we want. From there, we simply generate those combinations.

The real challenge is in efficiently generating the _n<sup>th</sup>_ lexicographical combination. For the standard combinations with/without replacement, this is quite trivial. However for multisets, it is much more complicated. It all comes down to counting.

You can see the algorithms for every case here (see the functions with `Gmp` in the name for the large cases you are referring to): https://github.com/jwood000/RcppAlgos/blob/master/src/NthResult.cpp

See these posts for more information:

  [Is there a function to generate a specific n Multichoose r combination, given the index number?](<https://stackoverflow.com/a/50177938/4408538>)
  [How to get the kth term in N Combination R](<https://stackoverflow.com/a/51848026/4408538>)

If you still have any questions, don't hesitate asking for clarification.
