### ISSUE TITLE
Question: permutations with variable-dependent bounds

### ISSUE THREAD

**Issue by tnyq** [jwood000/RcppAlgos#24]
Hi!

I'm working on a project where I have to create a weight matrix consisting of 9 variables. V1 must have a min weight of 1 and max weight of 5, while V2:V9 can have min weight 0 and max weight 3. I have tried to find an optimal solution to this problem by reading and implementing examples from the documentation, but as of now, the only way I can solve it is to create a "complete" weight matrix where all variables can have weights between 0 and 5, -then I remove all instances where V1==0 or V2:V9 >3.

Is there some functionality in RcppAlgo that would allow we to specify these variable-dependent constraint?

**Comment by jwood000** [comment]
@tnyq,

I think the best way to handle these types of problems is to build up your solution as generating all results and pruning can get expensive.

For your problem, I would generate the weight matrix for `V2:V9` first then add every possible weight for `V1`.

Here is a smaller example with four variables `V1:V4`, where `V1` can range from 1 to 3 and `V2:V4` can range from 0 to 1.

```r
library(RcppAlgos)

n_vars <- 4

## Weights for all variables except V1
aux <- comboGeneral(0:1, n_vars - 1, TRUE)

## Weights for V1
weights_v1 <- 1:3
v1 <- rep(weights_v1, each = nrow(aux))

## Combine results
weights <- matrix(c(v1, rep(aux, length(weights_v1))), ncol = n_vars)
colnames(weights) <- paste0("V", 1:n_vars)

weights
#       V1 V2 V3 V4
#  [1,]  1  0  0  0
#  [2,]  1  0  0  0
#  [3,]  1  0  0  0
#  [4,]  1  1  1  1
#  [5,]  2  0  0  0
#  [6,]  2  0  0  0
#  [7,]  2  1  1  1
#  [8,]  2  1  1  1
#  [9,]  3  0  0  0
# [10,]  3  1  1  1
# [11,]  3  1  1  1
# [12,]  3  1  1  1
```

This should be very efficient even if you need permutations. With `permuteGeneral` replaced above and your example variables/weights, the result was instant. The result had `327680` rows whereas if we were to generate all and prune we would need to sort out over 10 million permutations.

Hope this helps!

```r
permuteCount(0:5, 9, T)
# [1] 10077696
```

**Comment by tnyq** [comment]
Thank you so much for your reply! This will definitely help speed up the
process.

Best regards,
Thomas
