### ISSUE TITLE
What is the reason behind row limit?

### ISSUE THREAD

**Issue by drag05** [jwood000/RcppAlgos#25]
What is the reason behind row limit to 2^31 - 1?

Thank you!

**Comment by jwood000** [comment]
Hey @drag05,

Generally when you see `2^31 - 1`, it means integers are being used for indexing. Some containers have integer limits imposed on them as well.

See `INT_MAX` here: https://docs.microsoft.com/en-us/cpp/c-language/cpp-integer-limits?view=msvc-170.

You will note that it is `2147483647` which is equal to `2^31 - 1`.

Hope this helps
